### ISSUE TITLE
Deserializing empty payloads on MSG_SETTINGS_READ_BY_INDEX doesn't work

### ISSUE THREAD

**Issue by mfine** [swift-nav/libsbp#106]
```
>>> import sbp
>>> s = sbp.SBP(msg_type=0xA2, sender=1781, length=0, payload="", crc=0xCCE3)
>>> import sbp.table
>>> sbp.table.dispatch(s)
sbp/table.py:76: RuntimeWarning: SBP payload deserialization error! 0xa2
  RuntimeWarning)
<SBP (preamble=0x55, msg_type=0xA2, sender=1781, length=0, payload=, crc=0xCCE3)>
>>>
```

Not sure where or if the serialization is failing here, but came across this failure from a live log.

**Comment by mfine** [comment]
Hmm, this is just a bad message - needs a payload, according to our specs.

**Comment by fnoble** [comment]
There are some messages in the spec that can have two different payloads in different contexts. I made some notes on the doc about how to eliminate some of these, I think we should try to do that ASAP.
