### ISSUE TITLE
Remove init known baseline feature from console

### ISSUE THREAD

**Issue by cbeighley** [swift-nav/libsbp#116]
For the example of the headaches it causes:
https://groups.google.com/forum/#!topic/swiftnav-discuss/UpXC7QTub34

Closes swift-nav/piksi_firmware#370

**Comment by henryhallam** [comment]
While I'm potentially in favor of removing it from the console, I don't think it should be removed from SBP and Piksi.  There are potentially important embedded use cases for it.

**Comment by cbeighley** [comment]
Whoops yes I meant to file this under piksi_tools...
