### ISSUE TITLE
GPS Trace different than the ENU Trace

### ISSUE THREAD

**Issue by rahulmoorthy19** [swift-nav/libsbp#1195]
I am using a Swiftnav Duro to record a GPS and ENU Trace (NED converted to ENU). There was an observation that the GPS trace is much more different than the ENU trace. In particular, the GPS trace has a higher disturbance as compared to the ENU trace. I have added the images below for your reference. The top path is of the ENU while the bottom path is of the GPS.

The messages which I am accessing are SBP_MSG_POS_LLH for the RTK GPS values and SBP_MSG_BASELINE_NED for the NED Values which are converted to ENU.

Just wanted to understand 

why there is a difference in the GPS and the ENU trace if the source is the same. Would be grateful for the help.

![ENU_PATH](https://user-images.githubusercontent.com/32005497/180471723-e948027d-6a32-42d0-8c43-629fbf8c3011.png)
![GPS_PATH](https://user-images.githubusercontent.com/32005497/180471726-bde80869-ad5c-4563-83fb-0643f8b73797.png)

**Comment by silverjam** [comment]
Hello @rahulmoorthy19 -- would you mind forwarding your question to our support team via https://support.swiftnav.com/support/tickets/new?  We'll be able to get your question to the right people through this channel.  Thanks for being a Swift Navigation customer!
