### ISSUE TITLE
Missing GPS Week in sbp2report -ins.csv

### ISSUE THREAD

**Issue by rehrler** [swift-nav/libsbp#1234]
When generating csv using `sbp2report` from sbp files, the column GPS Week as observable in the solution csv is missing in the -ins.csv file. 

Just with GPS TOW [s] it's not possible to generate a UTC time. 

Please adjust `sbp2report`.

**Comment by silverjam** [comment]
Hello @rehrler thank you for the bug report— can you please open a support request at https://support.swiftnav.com/support/login?
