### ISSUE TITLE
[C++] MessageTrait: name attribute

### ISSUE THREAD

**Issue by Cerclique** [swift-nav/libsbp#1240]
Do you have any plan to add a new auto-generated attribute that would return the name of the current type as a string ? 

Perhaps something like this: 

```c++
template <>
struct MessageTraits<sbp_msg_utc_time_gnss_t> {
   ...
   static constexpr char* name = "sbp_msg_utc_time_gnss_t";
   ...
};
```

**Comment by silverjam** [comment]
No plans yet, but it should pretty easy to implement. I’ll see if we can get it onto our backlog.

**Comment by silverjam** [comment]
Hi @Cerclique -- this change has been merged, it will be released in the next minor release of the library.
