### ISSUE TITLE
decode sbp data

### ISSUE THREAD

**Issue by lucazimmer** [swift-nav/libsbp#1257]
Dear Sir or Madam,

as a result of a project of Tadano Demag GmbH, I am manufacturing a surveying system for load radius measurement on mobile and crawler cranes. The distance between the center of the crane and the crane tip is to be measured using GPS data. For this I use your Duro system, consisting of base and rover. I am very satisfied with the accuracy and the ease of use of the system.
To process the incoming data and create a program for distance measurement, I use the program ``node.js''. I managed to transfer data from a TCP/IP connection, but the data is not readable for me. 
I have already tried all programs in the JavaScript folder, but I did not get any result. For my calculation I only need the latitude and the longitude. 
I would be very grateful if you could help me with my problem.
With kind regard

Luca Zimmer

**Comment by silverjam** [comment]
Hello Luca, can you please open a support request at https://support.swiftnav.com/support/login? Thank you!
