### ISSUE TITLE
Unknown CMake command "add_link_options"

### ISSUE THREAD

**Issue by WCEarp** [swift-nav/libsbp#1320]
While compiling the SBP bindings for C, I get an `Unknown CMake command "add_link_options"` when using CMake 3.12 which is specified as the minimum required CMake version in the CMakeLists.txt.

I believe the add_link_options was introduced in CMake 3.13.

**Comment by silverjam** [comment]
Thanks for reporting, I've addressed this in https://github.com/swift-nav/libsbp/pull/1342
