### ISSUE TITLE
Week number is always 0 in Message Protection Level

### ISSUE THREAD

**Issue by marcomaida94** [swift-nav/libsbp#1340]
Hello, 

While using the `gps_time()` function I noticed that the Protection Level message always returns `0` in the week number field, although it returns a full `GpsTime`. 

By looking around in the code I found this comment:

https://github.com/swift-nav/libsbp/blob/871191939c5f4b78d007f1e705dc180604fd91ff/proto/navigation.proto#L707-L715

Which suggests that Protection Level is one of the messages containing only a `tow`.
I am wondering why the struct has a `wn` field, if it's set always to zero. 
I think that `gps_time()` should anyway return a simple `tow` for this message type. 

By checking my logs better, I see that this happens when the sender id is `4096`, while when it is `789`,  week number is populated. In any case, those messages coming from `4096` look zero-ed. So I am confused.

Best,
Marco

[log.txt](https://github.com/swift-nav/libsbp/files/11736219/logc.txt)

**Comment by silverjam** [comment]
Hi @marcomaida94 -- would you mind creating a support request at <https://support.swiftnav.com/support/tickets/new>?  This seems like an issue with Skylark's integrity output so the support portal is the best way to ensure that the question is routed to the right person.  I will flag this internally though so people know it's coming.  Thanks!
