### ISSUE TITLE
libsbp design document

### ISSUE THREAD

**Issue by mookerji** [swift-nav/libsbp#149]
As part of the forward compatibility considerations (and improving the code generation, extensibility, and robustness story) with libsbp, we should probably have a design document addressing some common pain points and maintainability issues that we'll have going forward. 

This is currently described in more detail here: 
https://swiftnav.hackpad.com/v1.0-Release-Forward-Compatibility-Considerations-CRCC44tzzZa

@cbeighley 's auditing the existing messages (i.e., bootloader stuff)
@mfine and I are going to look into more formal aspects (the goal being to preserve the existing messages and interfaces, but probably solidifying the code generation and the tooling around it)

Random References:
- https://www.usenix.org/conference/osdi14/technical-sessions/presentation/bangert
- https://github.com/jbangert/nail
- http://koti.kapsi.fi/jpa/nanopb/docs/concepts.html
- https://github.com/cognitect/transit-format
- Stability/versioning: http://www.u-blox.com/images/downloads/Product_Docs/u-blox6_ReceiverDescriptionProtocolSpec_(GPS.G6-SW-10018).pdf

/cc @cbeighley @mfine @fnoble

**Comment by mfine** [comment]
Captured current status of messages wrt public/private, stable/unstable [here](https://swiftnav.hackpad.com/SBP-Messages-Status-XS5xpWwhzwd).

Known messages responding with `MSG_PRINT` errors [here](https://swiftnav.hackpad.com/SBP-Messages-erring-with-MSG_PRINT-jX8Do75gKC0).
