### ISSUE TITLE
SBP documentation - add "integer" column for message id somewhere

### ISSUE THREAD

**Issue by denniszollo** [swift-nav/libsbp#163]
If you look at the JSON logs we product and ship around, the msg_type field is always shown as a base 10 integer, but in our documentation it is always shown in Hexadecimal.  To help your users, it may be useful to either add the base10 to the documentation, or encode our JSON with hexadecimal.

**Comment by mfine** [comment]
JSON doesn't support hexadecimal - so would have to be documentation oriented.
