### ISSUE TITLE
Promote Observations to Stable

### ISSUE THREAD

**Issue by mfine** [swift-nav/libsbp#165]
To reach SBP version 1.0, we should promote the observations messages to stable:

MSG_OBS
MSG_BASE_POS
MSG_EPHEMERIS

Move to the new PRN format for OBS messages. Validate ephemeris message contents - see table 20-iv in the ICD GPS 200.

/cc @mookerji @fnoble

**Comment by mfine** [comment]
Completion criteria: incorporate new PRN format and validate ephemeris message contents.

**Comment by mookerji** [comment]
We should probably have a short meeting discussing format changes later this week?

**Comment by mfine** [comment]
I'm going to catalog the the impacted messages and then setup a meeting.

**Comment by mfine** [comment]
Link to impacted messages:

https://swiftnav.hackpad.com/Mark-Fine-Notebook-XcC4ARL4VXE#:h=PRN-Widening-in-SBP

Meeting scheduled.

**Comment by mfine** [comment]
This is being completed by https://github.com/swift-nav/libsbp/pull/185.
