### ISSUE TITLE
Promote Settings to Stable

### ISSUE THREAD

**Issue by mfine** [swift-nav/libsbp#166]
To reach SBP version 1.0, we should promote the settings messages to stable:

MSG_SETTINGS
MSG_SETTINGS_SAVE
MSG_SETTINGS_READ_BY_INDEX

Insure their form and fitness for stability.

/cc @fnoble @mookerji @denniszollo

**Comment by mfine** [comment]
Ok, these messages are funky. They've got some weird edge cases and their bi-directionality is problematic. My proposal is that we:

1. Remove MSG_SETTINGS and replace it with a one-way MSG_SETTINGS_WRITE. This is always from the host to the device and has a payload of values to write.
2. MSG_SETTINGS_SAVE is unchanged
3. MSG_SETTINGS_READ_BY_INDEX gets replaced with MSG_SETTINGS_READ_HOST and MSG_SETTINGS_READ_DEVICE (the READ_DEVICE message takes READ_BY_INDEX's message id). READ_DEVICE always sends a string (no NULL).

Will put together some changes in sbp and firmware for this. Hope this will get us towards making these stable.

Thoughts?

**Comment by mookerji** [comment]
:+1: Consistent with the other request/response changes we're making. I'm checking out the ref'd PR now.

**Comment by mfine** [comment]
Ongoing PR's:

https://github.com/swift-nav/libsbp/pull/172
https://github.com/swift-nav/piksi_tools/pull/82
https://github.com/swift-nav/piksi_firmware/pull/449
