### ISSUE TITLE
Promote FileIO to Stable

### ISSUE THREAD

**Issue by mfine** [swift-nav/libsbp#175]
To reach SBP version 1.0, we should promote the file_io messages to stable:

MSG_FILEIO_READ
MSG_FILEIO_READ_DIR
MSG_FILEIO_REMOVE
MSG_FILEIO_WRITE

Insure their form and fitness for stability. In particular, remove bi-direction from these message. Presently,

FILEIO_READ
FILEIO_READ_DIR
FILEIO_WRITE

are bi-directional and confusing to use - we should introduce directionality:

FILEIO_READ_DEVICE
FILEIO_READ_HOST
FILEIO_READ_DIR_DEVICE
FILEIO_READ_DIR_HOST
FILEIO_WRITE_DEVICE
FILEIO_WRITE_HOST

/cc @mookerji @fnoble @cbeighley @denniszollo

**Comment by mookerji** [comment]
I'm all for fixing the request/response format here and possibly their payload specs, but don't feel great about making them stable, if only because they're really intended for internal use.

**Comment by denniszollo** [comment]
One question about FILEIO_WRITE_HOST.  I assume that this msg will be a confirmation message that the file was written (ie number of bytes), or an error string?

Additionally, might we consider allowing the piksi to log out information to another piksi or PC via these messages?  Or are we saying that these messages are strictly for writing to or reading from a Piksi's flash from a host?

**Comment by mfine** [comment]
Won't promote these to stable.

Not sure what the scope is for returning errors. There is precedence for returning `_DONE` here.

**Comment by mfine** [comment]
Completion criteria: new non-directional messages laid out.

**Comment by mfine** [comment]
Pull requests capturing this work:

https://github.com/swift-nav/libsbp/pull/183
https://github.com/swift-nav/piksi_tools/pull/84
https://github.com/swift-nav/piksi_firmware/pull/452
