### ISSUE TITLE
simple C client example of using SBP

### ISSUE THREAD

**Issue by denniszollo** [swift-nav/libsbp#180]
Should be for a normal PC with a POSIX serial library (not an embedded target).  Would be great if we got this in before 1.0.

cc @mfine @cbeighley @mookerji @fnoble

**Comment by henryhallam** [comment]
Serial code example: https://gist.github.com/henryhallam/31810c9ef54642c518d3 (includes various fault-handling stuff that is overkill for the SBP example)

**Comment by henryhallam** [comment]
Rates in excess of B115200 are supported on Linux and I think Windows but [not OSX](https://github.com/tomszilagyi/gen_serial/issues/1).  You can use some kind of IOKit workaround, but I think it would be OK to just guard it with #ifdef __linux__ and note that OSX users will have to use a lower baud, implement the workaround, or use FTDI's aliasing crap.

**Comment by gsmcmullin** [comment]
From pyserial it looks like OSX is quite easy to support:
```
elif plat[:6] == 'darwin':   # OS X

    version = os.uname()[2].split('.')
    # Tiger or above can support arbitrary serial speeds
    if int(version[0]) >= 8:
        def set_special_baudrate(port, baudrate):
            # use IOKit-specific call to set up high speeds
            import array, fcntl
            buf = array.array('i', [baudrate])
            IOSSIOSPEED = 0x80045402 #_IOW('T', 2, speed_t)
            fcntl.ioctl(port.fd, IOSSIOSPEED, buf, 1)
    else: # version < 8
        def set_special_baudrate(port, baudrate):
            raise ValueError("baud rate not supported")
```

**Comment by ungureanuvladvictor** [comment]
PR here: https://github.com/swift-nav/libsbp/pull/193
