### ISSUE TITLE
Pyserial appears to return the wrong description strings

### ISSUE THREAD

**Issue by soulcmdc-zz** [swift-nav/libsbp#186]
On Linux:

``` txt
Serial device '/dev/ttyUSB0' not found
The following serial devices were detected:

    /dev/ttyUSB1 (Linux Foundation 2.0 root hub )
```

However, lsub returns:

``` txt
Bus 002 Device 003: ID 05ac:8406 Apple, Inc. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 05ac:0259 Apple, Inc. 
Bus 001 Device 006: ID 05ac:8289 Apple, Inc. 
Bus 001 Device 002: ID 0a5c:4500 Broadcom Corp. BCM2046B1 USB 2.0 Hub (part of BCM2046 Bluetooth)
Bus 001 Device 034: ID 0403:6014 Future Technology Devices International, Ltd FT232H Single HS USB-UART/FIFO IC
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

An initial investigation seems to indicate that it's grabbing the correct VID:PID and tty name, but the correct description is not present.   It appears to be an issue with the python serial library. 

Maybe an approach more like http://stackoverflow.com/questions/12090503/listing-available-com-ports-with-python makes sense, although it seems much less elegant for such a small problem.

**Comment by mfine** [comment]
Oh interesting. Related, I kind of hate that this dumping of devices is in the error handling in the library :( Wish it was outside and that the exception was handled in the tools.
