### ISSUE TITLE
Python SBP bindings fail to parse current Obs messages with short PRNs

### ISSUE THREAD

**Issue by henryhallam** [swift-nav/libsbp#210]
In my specific case, I have piksi_firmware built with v0.48.0, running in HITL on mufasa where serial_link is using (I'm [pretty sure](http://zazu.ci.swiftnav.com/job/piksi_firmware_Log_Capture_2/32533/console)) SBP v0.49.0.  If I process the resulting json log on my PC with latest gnss_analysis and SBP v0.49.0, the MsgObs appear to get silently dropped - they don't even make it to process_message() in gnss_analysis:records2table.py in any form, neither MsgObs nor MsgObsDepA.  As far as I can tell, other messages make it through OK.  If I install SBP v0.48.0 on my PC, all is well.

If this behavior is expected that's fine I guess, just close this ticket WONTFIX

**Comment by mfine** [comment]
Huh, that definitely shouldn't be happening! Could it be something without your firmware build? I looked at some logs from capture 1, and there are MsgObsDepA log lines:

http://zazu.ci.swiftnav.com/job/piksi_firmware_Log_Capture_1/lastSuccessfulBuild/artifact/serial-link-20150711-205918.log.json/*view*/

But looking on capture 2, there are not messages:

http://zazu.ci.swiftnav.com/job/piksi_firmware_Log_Capture_2/lastSuccessfulBuild/artifact/serial-link-20150711-210111.log.json/*view*/

Off the top of me head, I can't think of how the serial link would just not log out obs messages.

**Comment by mfine** [comment]
Crickets. Don't think this was an issue. Closing.
