### ISSUE TITLE
Do something different with NaNs / Infs in json logger

### ISSUE THREAD

**Issue by henryhallam** [swift-nav/libsbp#214]
JSON doesn't, apparently, have a widely-supported means of encoding floating-point NaNs or infinities.  If Piski generates an SBP message containing one, presently json_logger.py (as used by the console and serial_link) will raise a RuntimeWarning and insert (the json.dumps of) an empty dict into the json output file.  This isn't ideal because
 - We might even want to use NaNs and inifnities to represent actual quantities.
 - Even if we try to avoid generating them, we'll still see them sometimes from bugs.  It'd be nice to know about it rather than the message just getting eaten before it makes it into the logfile.
 - The empty entry in the output, which lacks all the metadata fields like delta/timestamp/data/etc, breaks e.g. gnss_analysis:records2table.py

Maybe we could patch over all the NaNs in the message with some sentinel value, or zero, and set a flag field to label it as having had NaNs?  Or at least instead of inserting an empty message into the file, either don't insert one at all or insert a special one to mark that a whole message is missing due to NaNs.

cc @fnoble @mfine @mookerji

**Comment by henryhallam** [comment]
cc @peddie for teh luiz

**Comment by peddie** [comment]
Can't you just output `"NaN"`?  Everything is just a string anyway, right?  :P

P.S. I just checked, and `aeson` encodes and decodes `NaN` as a JSON `null`.
