### ISSUE TITLE
Sleep/wake failure on OSX with two Piksis attached

### ISSUE THREAD

**Issue by sashamitelman** [swift-nav/libsbp#279]
Doing my "first run" with a pair of Piksis attached to the same machine, I got some sort of OS exception when bringing the machine out of sleep. Stack trace below (saved as plain text).

[20151020_OSX_sleep-wake-failure_after_running_piksi_consoles.txt](https://github.com/swift-nav/libsbp/files/23608/20151020_OSX_sleep-wake-failure_after_running_piksi_consoles.txt)

**Comment by gsmcmullin** [comment]
Write to Apple and ask for your money back.

**Comment by jacobmcnamee** [comment]
I've had mouse/keyboard freeze ups several times when resuming with piksi connected. It might be related to the stream of "random" serial data. I have seen windows enumerate similar devices as serial mice, which is amusing but can be disabled.
