### ISSUE TITLE
Frame-less options

### ISSUE THREAD

**Issue by iorbitearth** [swift-nav/libsbp#314]
I have a custom framing protocol handled by hardware below the application, but I'm interested in utilizing C/python generator for structured messages. I may fork libsbp to remove the framing and strip down some of the built-in functionality. 

Any interest in what this would look like? Have you considered something like framing "plug-ins" that would allow users to define their own framing protocol or remove it entirely? I know it's outside the scope of Swift devices, but the work in place for defining message formats and autogenerating structs/classes is very attractive for other embedded projects.

**Comment by mookerji** [comment]
Hey @iorbitearth!

Great to hear that you're interested. I believe I've had similar conversations with @henryhallam from Planet, and that there are a lot of overlapping use cases for what's a pretty general problem for embedded binary protocols.

Regarding the generator itself: a lot of the existing code is very hacked together. We're planning on having an actually engineered solution (i.e., a flexible compiler), but probably not anytime soon. At least from the academic point of view, I'm definitely interested in hearing more about what you'd like to do with what's there and probably wouldn't mind collaborating on improvements.

That being said, certain parts of the framing protocol are actually flexible. The python and C libraries both have framing stuff separated out (see https://github.com/swift-nav/libsbp/blob/master/python/sbp/client/framer.py), but there are obviously lots of assumptions about what fields are present, etc. You could likely implement your own framer and your own `SBP`-like parent object that your message types could inherit from. Once you get to that point though, SBP (and PlanetBP) becomes instances of some more-general binary protocol compiler that should live on its own.

By the way, there's some related prior art with similar ideas, but are also worth reading about:
- https://github.com/janestreet/bin_prot
- https://people.csail.mit.edu/nickolai/papers/bangert-nail-langsec.pdf
- https://github.com/jbangert/nail
- https://github.com/abiggerhammer/hammer

Nail is probably the most similar, but seems to have a less usable message grammar than what's currently in `spec/`.

@mfine, @JoshuaGross : thoughts?

**Comment by mgiaco** [comment]
Hey @iorbitearth!

I have also a different framing protocol, but there are a lot of features in this lib as I can see which are really great. :+1: 

@mookerji it would be really great if the framing format could be changed in an easy way. I am searching for a libopenbp + framing :-)

**Comment by mookerji** [comment]
Hey @iorbitearth @mgiaco ,

Do you guys want to provide a basic spec and examples of your existing framing protocols?

**Comment by iorbitearth** [comment]
Our framing protocol is similar to SBP:

Field  | Size (bytes) | Purpose
------------- | ------------- | -------------
magic number  | 2 | Denotes start of frame transmission
length | 1 | Length of payload
destination |  2 | Unique ID of destination hardware
sequence | 2 | Value used to associate incoming/outgoing packets
type | 1 | They payload type
payload | n | Binary message data specific to `type` field

The CRC is stripped since error handling takes place in hardware.

Are you thinking about ways to generalize framing formats? It would be really interesting (and challenging) to allow users to define a yaml spec for their frame format and autogenerate a parser (kind of like GNU bison, but for binary data).

A more complex framing protocol worth looking at is CADU, used for packing CCSDS telemetry packets: http://www.sat.dundee.ac.uk/modisformat.html#cadu

**Comment by mgiaco** [comment]
Our framing protocol is also similar to SBP.

Field |	Size (bytes)	| Purpose
-------|------------------------|------------
Start ID |  1 | Denotes start of a new message
Device ID | 1 | To identify the sender (1 master and n slaves)
CMD | 1 | command of this message 
DLC| 2 | data length (bytes) of the payload
Data | n | binary payload of this message
CRC | 1 | crc over the whole message 

Mathias

**Comment by mookerji** [comment]
Ack, ok, sorry for the extended holiday delay, @mgiaco @iorbitearth:

One thing you could do is produce, on a separate fork, the changes that would be required to generalize the generator for your particular framing definition. Have you tried doing that? As it currently stands, there aren't many tasks except for navigating the generator code:

You'll need to define a YAML format for your framing protocol and then generate or generalize: https://github.com/swift-nav/libsbp/blob/master/python/sbp/msg.py#L66

and update some of the existing references to the SBP fields: https://github.com/swift-nav/libsbp/blob/master/python/sbp/utils.py#L16. The message deframer is hardcoded to SBP (https://github.com/swift-nav/libsbp/blob/master/python/sbp/client/framer.py#L97), but you could likely pass it a parser combinator of some kind that could work on a stream (or simply define an abstract class implemented by a particular protocol).

I think that would make it clear what SBP-specific things would have to change to support other framing protocols. I think then we could extract the current generator into a separate project (OpenBinaryProtocol?) that could be shared?

**Comment by mgiaco** [comment]
Okay that sounds great - I will have a look at that after i have finished some work on my firmware. And libopb sound also really great. 

thanks for your help

**Comment by mgiaco** [comment]
So I started today first I would like to understand the Code of libsbp. I looked at the simple clients but what I am missing is how to send a simple message with this lib. I didn´t get i to work. Can you give me a simple example. 

thx

**Comment by jck** [comment]
see also: http://kaitai.io
