### ISSUE TITLE
libsbp for own projects?

### ISSUE THREAD

**Issue by mgiaco** [swift-nav/libsbp#316]
Hello,

Can I use the libsbp for own commercial projects. I know i have to publish the changes if i made one - right?

thx 
mathias

**Comment by mookerji** [comment]
Hey @mgiaco , actually, I don't think you have to push your changes upstream (although we're happy to have contributions!): https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License. I do think if you use it, you do have to allow the use of libsbp to be modifiable by the end user. 

That being said, the library is intended to make it easy for commercial users to integrate with our GNSS receiver (http://swiftnav.com/piksi.html).

**Comment by mgiaco** [comment]
Hello,
Thanks for your quick response.
