### ISSUE TITLE
DOPS units are incorrect

### ISSUE THREAD

**Issue by denniszollo** [swift-nav/libsbp#347]
in the firmware we multiply the dops by 100 before sending on the wire.  We need to add that note as such in the document.

see sbp_make_dops() in sbp_utils.c in piksi firmware.

**Comment by ljbade** [comment]
Now fixed in SBP: https://github.com/swift-nav/libsbp/blob/01a7b4f93ade210cacb586c3c48fa32a2ee0093d/generator/tests/specs/sbp/navigation.yaml#L51
