### ISSUE TITLE
Create infrastructure for release of SBP sources only

### ISSUE THREAD

**Issue by denniszollo** [swift-nav/libsbp#372]
Generate source, versioning, add developer documentation, and host on web somehow
This source release would be linked to piksi_firmware versions

**Comment by JoshuaGross** [comment]
Tagged versions on github are source releases - and you can link directly to tarball downloads. Do we need something else?

**Comment by denniszollo** [comment]
It's not quite correct though because this has all the generator code in it which isn't required to use the library.

**Comment by denniszollo** [comment]
I also think that if someone wants the java bindings, they would prefer to only download the java bindings complete with a nice hello world example.

**Comment by denniszollo** [comment]
Decision made 03/07 by interested parties at Swift to do the following:
- If the language is released in a package repository we do nothing
- If no package repository (i.e. c and c++ or java)
    - we release and host tarball of sources
    - update makefile to do so
    - put on downloads.swiftnav.com
- Each language will have a landing page which will direct users to either get from the repository manager (i.e. pip install) or to go grab the tarball.
