### ISSUE TITLE
SID signal constants should be in "values:"

### ISSUE THREAD

**Issue by ljbade** [swift-nav/libsbp#405]
@denniszollo I'm sorry that I missed this during PR review, but in https://github.com/swift-nav/libsbp/blob/master/spec/yaml/swiftnav/sbp/gnss.yaml

I think we should move the list of signal codes from the "desc" field, to a "values" list under the code field itself, similar to other SBP messages with enum type fields.

We could copy the same list for both 16/32 bit versions of the GnssSignal type.

**Comment by denniszollo** [comment]
good idea.

 but right now the "values" thing doesn't do anything anyway as far as code generation so not much of a point at present.

**Comment by ljbade** [comment]
No, but we might eventually use the field to generate `#define` or something, just keeps things tidy/consistent for the moment.

**Comment by ljbade** [comment]
Moved to https://github.com/swift-nav/product_engr_planning/issues/133
