### ISSUE TITLE
Documentation no longer specifies HAE vs MSL for POS_LLH (0x0201)

### ISSUE THREAD

**Issue by cnelson711** [swift-nav/libsbp#409]
In v1.0 of SBP.pdf, bit 3 of the flags in POS_LLH (0x0201) differentiated between WGS-84 (the height above a mathematically defined perfect ellipsoid that GPS uses internally) and height about the mean sea level (the height above a wobbly, bumby, ball of mass that smoothly follows the geoid).  I've seen the difference between the two systems vary between 5 to 30 meters.

In v2.0, this was removed from the documentation.  Bit 3 is labeled "Reserved".

It seems pretty important to convey which mode is being output.

**Comment by ljbade** [comment]
@cnelson711 SBP 2.0 will currently only output HAE. The Piksi v2 (SBP 1.x) only ever outputs HAE as it did not have a built in geoid. That is why we decided to make this a reserved bit in the mean time.

I agree that we should at least state that height is in HAE for the moment.

/cc @denniszollo
