### ISSUE TITLE
Remove RAIM flag from position messages

### ISSUE THREAD

**Issue by denniszollo** [swift-nav/libsbp#414]
It was determined that RAIM flag isn't very useful

**Comment by ljbade** [comment]
@denniszollo Can you move this to the product engineering repo and add to the SBP 2.0 epic? Im trying to track remaining cleanup tasks in there.

**Comment by ljbade** [comment]
Issue moved to [swift-nav/product_engr_planning #145](https://github.com/swift-nav/product_engr_planning/issues/145) via [**ZenHub**](https://www.zenhub.com/)
