### ISSUE TITLE
crc mismatch Host Side Unhandled byte

### ISSUE THREAD

**Issue by raghad1234** [swift-nav/libsbp#428]
hi 
I'm trying to read the sbp data from piksi using Linux Ubuntu 14.04 terminal. I followed exactly the steps in the link below 
http://docs.swiftnav.com/wiki/Reading_SBP_data_from_Piksi_with_a_simple_client

piksi opened successfully, I can see this by running 
roslaunch swiftnav_piksi swiftnav_piksi.launch

and the piksi is sending the data through the USB cable but I always get the error below when running this command        python -m sbp.client.examples.simple -p /dev/ttyUSB0

crc mismatch: 0xE24B 0x0000
Host Side Unhandled byte: 0x07
Host Side Unhandled byte: 0x00
Host Side Unhandled byte: 0x1c
Host Side Unhandled byte: 0x02

Any hint? 

Thanks in advance

**Comment by ljbade** [comment]
First thing that comes to my mind is to check the baudrate of the serial port.

**Comment by ljbade** [comment]
For Piksi v2 the default serial baud rate is 1000000

**Comment by raghad1234** [comment]
Hi Leith, 

I used the default baud rate which is 1000000

Regards,
Raghad
________________________________________

**Comment by raghad1234** [comment]
By the way. I tried to run the console in Linux and it wasn't working. I usually change the piksi settings in windows and do the testing in linux .. Is there anything in  simple-clients libraries depend on console libraries?

**Comment by jkretzmer** [comment]
@raghad1234 - I have responded to you via our support system. Your initial request bounced due to a typo in the email address. Let's continue this discussion via the support system.

Thanks,
-Josh

**Comment by rajarout86** [comment]
I am also having the same issue. I am using Ubuntu 15.10 and upon the execution of  python -m sbp.client.examples.simple -p /dev/ttyUSB0 the following error occurs,
Host Side Unhandled byte: 0x00
Host Side Unhandled byte: 0x00

**Comment by sparky002** [comment]
I get the same error running that same script but my swiftnav console can connect fine to the device. Any ideas?

**Comment by daoyunxiong** [comment]
crc mismatch 0xD871 0x0000 ,  I can't get the fix rtk status , how to solve this problem , serial baud rate is 115200

**Comment by denniszollo** [comment]
The "Host Side Unhandled byte:" error indicates that there was some data on the wire that could not be interpreted as SBP.  If you modify the following line in the script to remove the verbose flag the message will go away: https://github.com/swift-nav/libsbp/blob/master/python/sbp/client/examples/simple.py#L36

The crc mismatch just indicates that you are dropping some information on the serial port or there is some bit error, which is something that should be expected occasionally.  For your other issue where you are having trouble getting RTK fix mode, please open a ticket on support.swiftnav.com with background information about what you are trying to do following these helpful hints. https://support.swiftnav.com/customer/en/portal/articles/2847992-requesting-support
