### ISSUE TITLE
Random Error in Pos_LLH

### ISSUE THREAD

**Issue by RaiBearG** [swift-nav/libsbp#455]
Apologies, if this repo is not the right place for this. 

Anyway, running some long duration static tests with piksi in RTK Fix mode(12 hours continuous) . Every 45 ish minutes the solution (Msg_Pos_LLH)  would jump to 30-50 cm from the original RTK position and come back to correct value in 15 ish minutes. No pattern really, sat count and radio communication were both consistent. 

Is this a known problem ? 

I forgot to log, but the next time I do, I'll upload them here. 

Rai

**Comment by cbeighley** [comment]
@RaiBearG Thanks for submitting this, we shall investigate
