### ISSUE TITLE
MSG_UART_STATE: status of uart A and B with all 0s

### ISSUE THREAD

**Issue by marco-tranzatto** [swift-nav/libsbp#472]
Hi,

I'm currently using SBP library v2.2.1 in python, and in my callback function for message SBP_MSG_UART_STATE I see only 0s in fields uart_a.XXX and uart_b.XXX. All the other fields seem to be filled properly.

Do you have any clue why it happens?

Thanks for your help.
Marco.

**Comment by kholtmann** [comment]
I actually have the same issue where fields uart_a.* and uart_b.* are filled with 0s.

Would also greatly appreciate some help.

Best regards
Kai

**Comment by silverjam** [comment]
Unfortunately, the location where this message is generated in Piksi Multi no longer has direct access to the UART, which is likely why the fields are zero... if this is still an issue please reopen this incident so we can understand your use case or contact support@swiftnav.com for assistance.
