### ISSUE TITLE
Java Build is Broken

### ISSUE THREAD

**Issue by jkablan** [swift-nav/libsbp#495]
I've executed the following 

git clone https://github.com/swift-nav/libsbp.git
cd libsbp
make java
cd java
gradle build

and the build task fails with the following. Looks like there are some missing packages / missing functions. 

'  gradle build
:compileJava
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/observation/CarrierPhase.java:19: error: package com.swiftnav.sbp.gnss_signal does not exist
import com.swiftnav.sbp.gnss_signal.*;
^
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/observation/MsgEphemeris.java:19: error: package com.swiftnav.sbp.gnss_signal does not exist
import com.swiftnav.sbp.gnss_signal.*;
^
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/observation/MsgEphemeris.java:117: error: cannot find symbol
    public GnssSignal sid;
           ^
  symbol:   class GnssSignal
  location: class MsgEphemeris
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/observation/ObsGPSTime.java:19: error: package com.swiftnav.sbp.gnss_signal does not exist
import com.swiftnav.sbp.gnss_signal.*;
^
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/tracking/MsgTrackingStateDetailed.java:127: error: cannot find symbol
        recv_time = parser.getU64();
                          ^
  symbol:   method getU64()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/tracking/MsgTrackingStateDetailed.java:138: error: cannot find symbol
        clock_offset = parser.getS16();
                             ^
  symbol:   method getS16()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/tracking/MsgTrackingStateDetailed.java:139: error: cannot find symbol
        clock_drift = parser.getS16();
                            ^
  symbol:   method getS16()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/tracking/MsgTrackingStateDetailed.java:141: error: cannot find symbol
        acceleration = parser.getS8();
                             ^
  symbol:   method getS8()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/tracking/MsgTrackingStateDetailed.java:152: error: cannot find symbol
        builder.putU64(recv_time);
               ^
  symbol:   method putU64(long)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/tracking/MsgTrackingStateDetailed.java:163: error: cannot find symbol
        builder.putS16(clock_offset);
               ^
  symbol:   method putS16(int)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/tracking/MsgTrackingStateDetailed.java:164: error: cannot find symbol
        builder.putS16(clock_drift);
               ^
  symbol:   method putS16(int)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/tracking/MsgTrackingStateDetailed.java:166: error: cannot find symbol
        builder.putS8(acceleration);
               ^
  symbol:   method putS8(int)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/imu/MsgImuAux.java:59: error: cannot find symbol
        temp = parser.getS16();
                     ^
  symbol:   method getS16()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/imu/MsgImuAux.java:66: error: cannot find symbol
        builder.putS16(temp);
               ^
  symbol:   method putS16(int)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/imu/MsgImuRaw.java:77: error: cannot find symbol
        acc_x = parser.getS16();
                      ^
  symbol:   method getS16()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/imu/MsgImuRaw.java:78: error: cannot find symbol
        acc_y = parser.getS16();
                      ^
  symbol:   method getS16()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/imu/MsgImuRaw.java:79: error: cannot find symbol
        acc_z = parser.getS16();
                      ^
  symbol:   method getS16()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/imu/MsgImuRaw.java:80: error: cannot find symbol
        gyr_x = parser.getS16();
                      ^
  symbol:   method getS16()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/imu/MsgImuRaw.java:81: error: cannot find symbol
        gyr_y = parser.getS16();
                      ^
  symbol:   method getS16()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/imu/MsgImuRaw.java:82: error: cannot find symbol
        gyr_z = parser.getS16();
                      ^
  symbol:   method getS16()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/imu/MsgImuRaw.java:89: error: cannot find symbol
        builder.putS16(acc_x);
               ^
  symbol:   method putS16(int)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/imu/MsgImuRaw.java:90: error: cannot find symbol
        builder.putS16(acc_y);
               ^
  symbol:   method putS16(int)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/imu/MsgImuRaw.java:91: error: cannot find symbol
        builder.putS16(acc_z);
               ^
  symbol:   method putS16(int)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/imu/MsgImuRaw.java:92: error: cannot find symbol
        builder.putS16(gyr_x);
               ^
  symbol:   method putS16(int)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/imu/MsgImuRaw.java:93: error: cannot find symbol
        builder.putS16(gyr_y);
               ^
  symbol:   method putS16(int)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/imu/MsgImuRaw.java:94: error: cannot find symbol
        builder.putS16(gyr_z);
               ^
  symbol:   method putS16(int)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/observation/Doppler.java:39: error: cannot find symbol
        i = parser.getS16();
                  ^
  symbol:   method getS16()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/observation/Doppler.java:47: error: cannot find symbol
        builder.putS16(i);
               ^
  symbol:   method putS16(int)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/observation/MsgGroupDelayDepA.java:69: error: cannot find symbol
        tgd = parser.getS16();
                    ^
  symbol:   method getS16()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/observation/MsgGroupDelayDepA.java:70: error: cannot find symbol
        isc_l1ca = parser.getS16();
                         ^
  symbol:   method getS16()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/observation/MsgGroupDelayDepA.java:71: error: cannot find symbol
        isc_l2c = parser.getS16();
                        ^
  symbol:   method getS16()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/observation/MsgGroupDelayDepA.java:79: error: cannot find symbol
        builder.putS16(tgd);
               ^
  symbol:   method putS16(int)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/observation/MsgGroupDelayDepA.java:80: error: cannot find symbol
        builder.putS16(isc_l1ca);
               ^
  symbol:   method putS16(int)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/observation/MsgGroupDelayDepA.java:81: error: cannot find symbol
        builder.putS16(isc_l2c);
               ^
  symbol:   method putS16(int)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/observation/MsgEphemeris.java:164: error: cannot find symbol
        sid = new GnssSignal().parse(parser);
                  ^
  symbol:   class GnssSignal
  location: class MsgEphemeris
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/observation/MsgGroupDelay.java:69: error: cannot find symbol
        tgd = parser.getS16();
                    ^
  symbol:   method getS16()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/observation/MsgGroupDelay.java:70: error: cannot find symbol
        isc_l1ca = parser.getS16();
                         ^
  symbol:   method getS16()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/observation/MsgGroupDelay.java:71: error: cannot find symbol
        isc_l2c = parser.getS16();
                        ^
  symbol:   method getS16()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/observation/MsgGroupDelay.java:79: error: cannot find symbol
        builder.putS16(tgd);
               ^
  symbol:   method putS16(int)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/observation/MsgGroupDelay.java:80: error: cannot find symbol
        builder.putS16(isc_l1ca);
               ^
  symbol:   method putS16(int)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/observation/MsgGroupDelay.java:81: error: cannot find symbol
        builder.putS16(isc_l2c);
               ^
  symbol:   method putS16(int)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/ndb/MsgNdbEvent.java:84: error: cannot find symbol
        recv_time = parser.getU64();
                          ^
  symbol:   method getU64()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/ndb/MsgNdbEvent.java:96: error: cannot find symbol
        builder.putU64(recv_time);
               ^
  symbol:   method putU64(long)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/loggers/JSONLogger.java:33: error: incompatible types: String cannot be converted to long
        starttime = ISOTimestamp();
                                ^
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/loggers/JSONLogger.java:40: error: cannot find symbol
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
                            ^
  symbol:   class SimpleDateFormat
  location: class JSONLogger
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/loggers/JSONLogger.java:42: error: cannot find symbol
        String asISO = df.format(new Date());
                                     ^
  symbol:   class Date
  location: class JSONLogger
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/piksi/MsgDeviceMonitor.java:65: error: cannot find symbol
        dev_vin = parser.getS16();
                        ^
  symbol:   method getS16()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/piksi/MsgDeviceMonitor.java:66: error: cannot find symbol
        cpu_vint = parser.getS16();
                         ^
  symbol:   method getS16()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/piksi/MsgDeviceMonitor.java:67: error: cannot find symbol
        cpu_vaux = parser.getS16();
                         ^
  symbol:   method getS16()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/piksi/MsgDeviceMonitor.java:68: error: cannot find symbol
        cpu_temperature = parser.getS16();
                                ^
  symbol:   method getS16()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/piksi/MsgDeviceMonitor.java:69: error: cannot find symbol
        fe_temperature = parser.getS16();
                               ^
  symbol:   method getS16()
  location: variable parser of type SBPMessage.Parser
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/piksi/MsgDeviceMonitor.java:74: error: cannot find symbol
        builder.putS16(dev_vin);
               ^
  symbol:   method putS16(int)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/piksi/MsgDeviceMonitor.java:75: error: cannot find symbol
        builder.putS16(cpu_vint);
               ^
  symbol:   method putS16(int)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/piksi/MsgDeviceMonitor.java:76: error: cannot find symbol
        builder.putS16(cpu_vaux);
               ^
  symbol:   method putS16(int)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/piksi/MsgDeviceMonitor.java:77: error: cannot find symbol
        builder.putS16(cpu_temperature);
               ^
  symbol:   method putS16(int)
  location: variable builder of type SBPMessage.Builder
/home/qwerty/software/libsbp/java/src/com/swiftnav/sbp/piksi/MsgDeviceMonitor.java:78: error: cannot find symbol
        builder.putS16(fe_temperature);
               ^
  symbol:   method putS16(int)
  location: variable builder of type SBPMessage.Builder
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
56 errors
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
'

**Comment by ljbade** [comment]
Sorry about this, I will get someone to take a look. I will also see if we can add the gradle build to our Travis test

**Comment by ljbade** [comment]
@gsmcmullin is going to take a look at this. He has an open PR https://github.com/swift-nav/libsbp/pull/442

**Comment by broswen** [comment]
What is the status of this issue (or the PR )? I would like to use the Java implementation in an Android app but the branch still fails to build.

**Comment by mfine** [comment]
@jkablan @broswen sorry for the delay in getting this resolved - java build should be building on master now!
