### ISSUE TITLE
No messages print out when run simple.py

### ISSUE THREAD

**Issue by hbsun7** [swift-nav/libsbp#497]
I use Python 2.7 and run the simple.py. But no messages come out. Framer information from my Pikisi v2 GPS is right. I think the problem might be in the handler. Does someone have the same problem?

**Comment by hbsun7** [comment]
I have figured out the problem. Message type with a "DepA" should be used for my piksi v2 gps.

**Comment by ljbade** [comment]
Sorry @hbsun7 are you waiting for simple.py to support Piksi v2? You can check out an older branch of this repo that supports v2 if you need that

**Comment by obbila** [comment]
which branch?

**Comment by ljbade** [comment]
@dzollo What release was the last version that supported Piksi v2? I'm thinking https://github.com/swift-nav/libsbp/blob/v1.2.8/CHANGELOG.md

**Comment by dzollo** [comment]
On the support site we say v0.52.4

D

**Comment by ljbade** [comment]
@hbsun7 @obbila this is the branch to use https://github.com/swift-nav/libsbp/tree/v0.52.4
