### ISSUE TITLE
Piksi GPS setting reading using Java

### ISSUE THREAD

**Issue by hbsun7** [swift-nav/libsbp#502]
Can anyone give me an example about readinng the setting from piksi gps using Java? For example, section="surveyed_position", setting="broadcast". Thank you so much!

**Comment by hbsun7** [comment]
I have figured out one solution: 
SBPMessage msg = new SBPMessage(0x42,MsgSettingsReadReq.TYPE,byteArray); //construct the SBPMessage
piksiframer.sendMessage(msg);                                                                                  //send the message
piksihandler.addCallback(MsgSettingsReadResp.TYPE, BaseCallback);                //get the feedback message

**Comment by ljbade** [comment]
@hbsun7 You might want to call `addCallback` before `sendMessage`

Sorry for not getting a reply to you sooner, but our Java expert was away.

**Comment by hbsun7** [comment]
@ljbade Thanks a lot for your information!
