### ISSUE TITLE
python example for piksi v2.3.1 Error Host Side Unhandled byte: 0x44

### ISSUE THREAD

**Issue by obbila** [swift-nav/libsbp#508]
Hi

I have been trying to run the python example:

python -m sbp.client.examples.simple -p /dev/[ttyUSB0]

I have tried this on Linux and Mac and I get the same problem

Host Side Unhandled byte: 0x44

I have tried this with a python sap bindings I installed back in January 2017 and one I installed today and I get the same result. 

I have got this example working in the past so I am a little confused why I have this problem

Any help would be most welcome.

Oliver

**Comment by denniszollo** [comment]
Oliver, Please see my latest response in #428 .  This message is not necessarily indicative of an error.  Please double check that the baudrate you are using matches that on the device and that you are connected to an interface that includes the message for which that the simple client is listening.
