### ISSUE TITLE
Feature request for SBP 2.2.15

### ISSUE THREAD

**Issue by kholtmann** [swift-nav/libsbp#527]
Hi

We are currently using the SBP library 2.2.15 for our [ethz_piksi_ros](https://github.com/ethz-asl/ethz_piksi_ros/) interface. There are two features we believe are missing in this current library version:

1.  A UART status message: for debugging it is crucial that we know the UART state, i.e., we want to know how many messages are sent / received.
2. We want to always have SPP and RTK information available. Currently, if Piksi is in a RTK Float or RTK Fix mode, no SPP messages are broadcasted. However, we want to always have SPP information and RTK on top of that, once (float or fix are) available.

We hope, that these features will be implemented into the library, since at least feature "2" should be very feasible, as SPP information is available at all times anyway. Also, both of these features were already available with Piksi V2.

Thanks in advance
Kai

**Comment by denniszollo** [comment]
Thanks so much for the feature request and feedback.  

We agree that item 1 was overlooked when we transitioned to Piksi Multi, but it unfortunately has some technical issues that make it hard for us to do quickly.  We hope to address it in future.

Item 2 we hope to also enable in the future, but it will probably be through a separate message_id that you can subscribe to which would provide the "SPP solution all day every day."  Please let me know if that would address the request.

I will try and respond to this issue to keep you updated as we plan and commit to addressing your requests.

**Comment by kholtmann** [comment]
Thank you for the reply.

Yes, this indeed addresses my request. I have one follow-up question, concerning the estimated implementation time of these two features; will it be in the next few weeks or rather months?

Thanks again in advance
Kai

**Comment by denniszollo** [comment]
I think unfortunately it is months away

**Comment by marco-tranzatto** [comment]
Hi @denniszollo do you have any update on this ?

Cheers,
Marco.
