### ISSUE TITLE
Publish v2.3.15 as a release

### ISSUE THREAD

**Issue by kanishkegb** [swift-nav/libsbp#573]
Swiftnav [SBP page](https://support.swiftnav.com/customer/en/portal/articles/2492810-swift-binary-protocol) shows that the latest release is v2.3.15. When I contacted Swiftnav tech support, they said for GPS firmware v1.5.12, I should be using SBP v2.3.15. 

Even though a tag for v2.3.15 has been created, it has not been marked as a release. Given that there are few modes added to the GPS firmware, it is important to update SBP firmware. Can you please mark the version as a release?

**Comment by denniszollo** [comment]
This has now been done.  Sorry it took so long!
