### ISSUE TITLE
No moduled named 'handler'

### ISSUE THREAD

**Issue by ChaosCA** [swift-nav/libsbp#574]
Importing the SBP Python client will raise a module not found error from inside SBP.

```python
Traceback (most recent call last):
  File "/home/b/Development/swiftnav-gps/Software/rpi-rover/main.py", line 4, in <module>
    from sbp.client.drivers.pyserial_driver import PySerialDriver
  File "/home/b/.pyenv/versions/rpi-rover/lib/python3.6/site-packages/sbp/client/__init__.py", line 11, in <module>
    from handler import Handler
ModuleNotFoundError: No module named 'handler'
```

You can reproduce this by trying the example code here: https://github.com/swift-nav/libsbp/blob/master/python/sbp/client/examples/simple.py

Is there any work around?

**Comment by adhityadwi** [comment]
Hello, which python version that you're using?

**Comment by ChaosCA** [comment]
The issue occurs in Python 3.6, not in Python2

**Comment by silverjam** [comment]
@ChaosCA release 2.5.0 has support for Python 3 so it should resolve this, please reopen this issue or contact support@swiftnav.com if anything else arises.
