### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by damouse** [swift-nav/libsbp#600]
Python 2 [end of life](https://pythonclock.org/) is just over a year out. 

My organization makes heavy use of your hardware and love what we can do with it, but we have to hack libsbp on every release to make it work again with Python 3-- the only python we use. I would push these hacks upstream, except that they *are* hacks-- sloppy, dangerous, and written with a lot of grumbling. Given that the version of python you support is losing official support in about a year, do you have any plans to begin supporting Python 3?

**Comment by denniszollo** [comment]
Thanks for reminding us of this action.  We will happily review and merge any pull request that simultaneously supports python2 and python3.  We do have a branch that supports python 3 already and does so in a not so hacky way, but we have not been rebasing it each release: https://github.com/swift-nav/libsbp/tree/jck/python3

**Comment by silverjam** [comment]
Python 3 support is available in release 2.5.0, please re-open this issue if you encounter issues or contact support@swiftnav.com.
