### ISSUE TITLE
Problem when casting messages from callback in C

### ISSUE THREAD

**Issue by feemi** [swift-nav/libsbp#611]
I use version 2.4.1 and communicate piksi according to c example. But when i cast msg to data type values are irrelevant. But when i access value directly from byte array it seems correct.

MSG_POS_LLH message
Example: msg[32] for n_sats -> it returns correct value

bad example:
/ msg_pos_llh_t *position_message = (msg_pos_llh_t* ) &msg;
position_message->lat
position_message->lon
position_message->n_sats 
none of the above returns correct vaue.

Could this problem be related to little-endian thing ?

**Comment by denniszollo** [comment]
Yes.  the library should parse each field separately doing byte swapping as necessary, but it currently does not.  On what system are you trying to use the library?

**Comment by feemi** [comment]
Thanks we already manage to parse them seperately for now. Do you plan to implement this in near future? Is this in your tech debt? We are using piksi on linux machine.

**Comment by denniszollo** [comment]
This won't be imminent, but I am hoping to do by end of year.

**Comment by denniszollo** [comment]
@feemi feemi, could you please describe better the linux machine you are using (i.e. what instruction set or processor is in use and what linux operating system)?  We are going to start prioritizing this work and I would love to learn from you use case to setup test cases in such a way that they are relevant to a real user.

**Comment by silverjam** [comment]
Create an internal issue for this: https://swift-nav.atlassian.net/browse/ESD-1287 -- please re-open if you have more feedback!
