### ISSUE TITLE
link to Piksi settings in sbp.settings module doc is really outdated

### ISSUE THREAD

**Issue by denisng** [swift-nav/libsbp#626]
doc page https://swift-nav.github.io/libsbp/python/docs/build/html/sbp.settings.html has a link to a settings.pdf that is really outdated.

Should point to Piksi Multi "Software Settings Manuals" in support pages (https://support.swiftnav.com/customer/en/portal/articles/2628580-piksi-multi-specifications)

**Comment by denniszollo** [comment]
I pushed the latest libsbp docs to the github.io page so this is now fixed.
http://swift-nav.github.io/libsbp/
@nicolekelley 
Can you add a task list to the release checklist to push the latest generated libsbp documentation to github.io branch "gh-pages"?

**Comment by nicolekelley** [comment]
@denniszollo  - done
