### ISSUE TITLE
MSG_INIT_BASE / Hotstart with known Position

### ISSUE THREAD

**Issue by michaelpantic** [swift-nav/libsbp#681]
Hi,

We're using and developing the https://github.com/ethz-asl/ethz_piksi_ros package for use on our Robots. Know we've come across a use case were a GPS receiver might loose view to the horizon for some time, but we still have relatively accurate position estimation in ENU frame through other means ( Visual-Inertial Odometry). 
Additionally, we want RTK-GPS to restore as fast as possible (every second counts!) after loosing it.

Is there a way to hotstart the Piksi Multi with a known baseline? I've found the MSG_INIT_BASE message, is that still in use on the Piksi Multi and how is the baseline sent to the piksi?

If this is not implemented, it would definitely be a very useful extension for us robotics people.

Thanks much for your help!

**Comment by swiftnav-sarika** [comment]
Hello @michaelpantic 
 
Piksi Multi does not support hot start currently and it is currently not on our roadmap for future releases. The MSG_INIT_BASE is no longer supported in SBP messages. Please refer to SBP document here, https://support.swiftnav.com/customer/en/portal/articles/2492810-swift-binary-protocol. 

We appreciate you reaching out to us with this feature request and feedback. Please feel free to request additional support from the website here, https://support.swiftnav.com/. 

Thanks!

**Comment by silverjam** [comment]
Added an internal issue to deprecate this message and update the sbp docs: https://swift-nav.atlassian.net/browse/ESD-1286

**Comment by michaelpantic** [comment]
Thanks much for the quick response!

Too bad, it really would be a large advantage over other RTK systems, as many applications do use RTK GPS as a drift-free additional estimation to an existing state estimation stack. Especially for transitioning indoor-outdoor and likewise use cases it just would make sense to use a baseline prior to hot-start IAR.

At least in our experience the unpredictable/uninfluencable "time-to-fix" after loss is probably the largest impediment for tighter integration into our state estimation/mapping stack for autonomous UAVs.
If you plan to introduce that feature / or willing to provide lower level access in exchange for some testing of the feature, don't hesitate to reach out to us!

**Comment by michaelpantic** [comment]
@marco-tranzatto @kholtmann FYI
