### ISSUE TITLE
v_accuracy and h_accuracy in the ros topic "piksi/pos_llh"

### ISSUE THREAD

**Issue by caseypen** [swift-nav/libsbp#718]
In the rostopic "piksi/pos_llh", two of the variables in the message are v_accuracy and h_accuracy. May I know what the meaning of these two variables?

**Comment by dombpala** [comment]
Hello! I also wanted to know. What are these variables and why are their values 0 in all the messages I receive from Piksi?

**Comment by caseypen** [comment]
You can check Piksi SBP protocol and they have the explanation there. Basically, they are relevant to the accuracy of the GPS localization result.

**Comment by silverjam** [comment]
> In the rostopic "piksi/pos_llh", two of the variables in the message are v_accuracy and h_accuracy. May I know what the meaning of these two variables?

This is documented in the SBP protocol specification, which you can find [on our support portal](https://support.swiftnav.com/support/solutions/articles/44001850782-swift-binary-protocol) with [v2.7.4](https://www.swiftnav.com/resource-files/Swift%20Navigation%20Binary%20Protocol/v2.7.4/Specification/Swift%20Navigation%20Binary%20Protocol%20Specification%20v2.7.4.pdf) being the current version for the Piksi Multi v2.4.15 -- the v_accuracy and h_accuracy fields are part of the POS_LLH message:

![Screenshot 2020-12-12 165208](https://user-images.githubusercontent.com/183436/102000252-67db7d80-3c9a-11eb-8de4-262216285830.png)

Please see our support portal for more information: https://support.swiftnav.com/support/home -- or feel free to contact support: https://support.swiftnav.com/support/tickets/new.

**Comment by denniszollo** [comment]
You may consider reading this article on support.swiftnav.com which is an application not intended to help with usage of such fields.

https://support.swiftnav.com/a/solutions/articles/44002097796
