### ISSUE TITLE
sbp2rinex does not generate valid rinex when using toJson() method from SBPMessage.java 

### ISSUE THREAD

**Issue by vitalate** [swift-nav/libsbp#720]
When receiving SBP messages using libsbp java client and then printing the JSON of received SbpMessages to a file, it is impossible to use sbp2rinex on this file. This happens because the toJson method does not include the CRC field on the output being impossible to generate a valid rinex.

**Comment by silverjam** [comment]
For a more long term solution the SBPHandler class should populate a CRC field in the SBPMessage class, but if making the CRC16 class and methods public works around this issue, then that is fine in the interim.

**Comment by silverjam** [comment]
Closing since we merged the requested change.  Please re-open if the more permanent solution is needed.
