### ISSUE TITLE
Rust parser does not continue parsing after CRC error

### ISSUE THREAD

**Issue by stabler** [swift-nav/libsbp#793]
When a ParserError occurs, the rust parser correctly advances the buffer: 
https://github.com/swift-nav/libsbp/blob/master/rust/sbp/src/parser/mod.rs#L138

However, other error types (including a CRC error) do not advance the buffer. Subsequent calls to .parse() will parse the same data and continue to return the same error type. The buffer is still full, so read_more will not be called.

**Comment by silverjam** [comment]
Thanks for reporting this issue!  Can you describe how you're invoking the parser that's causing this issue to manifest?

**Comment by silverjam** [comment]
We have a potential fix in https://github.com/swift-nav/libsbp/pull/798 -- if you'd like to try it out you can reference the fix branch in your Cargo.toml:

```
[dependencies.libsbp]
git = "https://github.com/swift-nav/libsbp.git"
rev = "6280860ebb6dfa46bb163b3287639c9b35f01dd4"
```

**Comment by stabler** [comment]
Hi Jason- I just tested (sorry for the delay), works great for me! Thanks

**Comment by silverjam** [comment]
@stabler Great!  Glad to hear it!
