### ISSUE TITLE
cmake/common/* missing in source archives

### ISSUE THREAD

**Issue by seezer** [swift-nav/libsbp#862]
Hi!

The source archives seem to miss the cmake/common contents.
All the way from https://github.com/swift-nav/libsbp/archive/v3.4.2.tar.gz back to at least https://github.com/swift-nav/libsbp/archive/v3.1.1.tar.gz

**Comment by silverjam** [comment]
Apparently this is a limitation of GitHub's source archives: https://github.com/dear-github/dear-github/issues/214 -- you can find the current code for our cmake modules here: https://github.com/swift-nav/cmake (these are generally backwards compatible so any version you pull should work)-- alternately you can clone everything with git including the cmake submodule with the `--recursive` switch:

```
git clone --recursive https://github.com/swift-nav/libsbp.git
```
