### ISSUE TITLE
Write GPSD driver for SBP

### ISSUE THREAD

**Issue by henryhallam** [swift-nav/libsbp#94]

**Comment by denniszollo** [comment]
+1 - this might be very helpful for demos and visualizations as well

**Comment by rikba** [comment]
Here is just a user experience on this issue. 
We are using Piksi Multi with to [synchronize against its PPS](https://github.com/ethz-asl/ethz_piksi_ros/pull/80) signal. Currently, we use the NMEA output to feed GPSD but I assume it would be better defined to use the native SBP.
